
name: Build and Test Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Corrigido para 'temurin', a distribuição do OpenJDK

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies with Maven
        run: mvn clean install -DskipTests=true  # Baixando as dependências sem rodar os testes ainda

      - name: Run tests with Maven
        run: mvn test  # Agora rodando os testes após as dependências estarem resolvidas
